feat/migrate to xterm.js 5.3.0
OmarTawfik/terminal-screenshot pull request #10
Opened 2024-01-30 20:05 UTC by edouard-lopez

- refactor: split `lint` script into `lint`, `compile` and `test
- chore: update packages setup eslint and simplify prettier config as we use default
- feat(xterm): migrate to 5.3.0

2024-01-31 15:05 UTC, OmarTawfik requested changes
@edouard-lopez thank you so much for looking into the xterm migration!
However, I suggest not mixing this upgrade with other drive-by changes, that are not required/related.

Thoughts about keeping this PR minimal to just the upgrade? we can discuss any infra/tooling related changes separately. Afterwards, I would be happy to test it and release a new version.

Thanks!

2024-02-01 09:21 UTC, edouard-lopez commented
I restrict the MR to a commit bumping `xterm` and the related update. I will push another MR for the tooling

Do you have constraints on the tooling versions? Do you have external tests?

2024-02-01 11:41 UTC, OmarTawfik requested changes
Thank you for looking into this!

I pulled it and ran the tests locally. Existing tests (comparing against static images) are passing except one:

```log

  ● can render error-message

    Expected image to match or be a close match to snapshot but was 11.925925925925926% different from snapshot (644 differing pixels).
    See diff for details: /var/folders/wf/m183hpcj025f1psz6nlsl83r0000gn/T/error-message-diff.png
```

And here is the diff:

![error-message-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/15987992/f055dcaa-5f0d-4f5c-a98c-fe4b067c269e)

I wonder if it is passing for you?
Maybe we just need to update the static images, as there might be glyph/character differences because of the upgrade.

2024-02-01 13:45 UTC, edouard-lopez commented
I checked again by rebuild the one from `main` from a clean slate:

```
❯ git checkout main
❯ rm yarn.lock node_modules/ -rf
❯ rm tests/screenshots/* 
❯ yarn install --frozen-lockfile
❯ jest tests/screenshots.test.ts
```

Then back on the feature branch
```
❯ git checkout feat/migrate-to-xterm.js-5.3.0
❯ rm yarn.lock node_modules/ -rf
❯ yarn install --frozen-lockfile
❯ jest tests/screenshots.test.ts
```

All are failing
![white-background-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/18103419-b066-4b3f-9a53-0907282e654a)
![emojis-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/293a10ef-bf78-4a56-a348-4aecc6d0b8d8)
![error-message-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/50cd02a1-98c9-4609-a423-6ea22d89e8dd)
![custom-background-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/c176e5e1-2fb8-4f97-96b9-c848b84877d8)
![custom-margin-diff](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/aa5a22e1-8939-4d4a-ac49-2a3b04ca5309)

Looking closer, the `!` (exclamation point) and `.` final dot are missing

2024-02-01 13:51 UTC, edouard-lopez commented
The template I got for the `error-message` test:

```html
<div class="xterm-rows" style="line-height: normal; letter-spacing: 0px;" aria-hidden="true">
    <div style="width: 270px; height: 17px; line-height: 17px; overflow: hidden;">
        <span class="xterm-fg-1">ERROR:</span>
        <span class="xterm-fg-8"> something went wrong!!</span>
        <span class="xterm-cursor xterm-cursor-outline xterm-fg-8">!</span>
    </div>
</div>
```

There is something weird happening with the cursor it seems
![image](https://github.com/OmarTawfik/terminal-screenshot/assets/1212392/4382c30f-a81b-4b34-9c08-2651b602248e)

2024-02-01 14:43 UTC, edouard-lopez commented
@OmarTawfik Could you check again, I believe it was due to the way you hide the cursor that was not behaving in the same way with `5.3.0`. 

I set [`cursorInactiveStyle: none`](https://github.com/xtermjs/xterm.js/releases/tag/5.3.0)  introduced in `5.3.0` instead

2024-02-02 18:37 UTC, OmarTawfik commented
@edouard-lopez  Thank you for the investigation. I did some digging and discovered a couple of issues (fixed in #16). Please feel free to rebase, and it should be able to run/test successfully now.

2024-02-05 09:55 UTC, edouard-lopez commented
Rebased and fixed a bug in CI, due to @ts-node

2024-02-06 00:02 UTC, OmarTawfik commented on yarn.lock
> +"@ampproject/remapping@^2.2.0":
This PR changes the entire `yarn.lock` from `yarnpkg` registry to `npmjs` .. I wonder if you have custom local overrides (e.g. `yarnrc`). If not, I suggest reverting these changes, and undoing changes to this file and rerunning `yarn` with vanilla settings.

2024-02-07 09:28 UTC, edouard-lopez commented
I rebased following #14 merge

2024-02-07 21:41 UTC, OmarTawfik approved these changes
Looks great!
Thank you.

2024-02-07 21:42 UTC, merged